<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/Yacht/Schemas/ContactAgeDays/ContactAgeDays.cs" Condition="Exists('$(PkgPath)/Yacht/Schemas/ContactAgeDays/ContactAgeDays.cs')" />
		<Compile Include="$(PkgPath)/Yacht/Schemas/TrafficLight/TrafficLight.cs" Condition="Exists('$(PkgPath)/Yacht/Schemas/TrafficLight/TrafficLight.cs')" />
		<Compile Include="$(PkgPath)/Yacht/Schemas/Yacht/Yacht.cs" Condition="Exists('$(PkgPath)/Yacht/Schemas/Yacht/Yacht.cs')" />
		<Compile Include="$(PkgPath)/Yacht/Schemas/YachtDriveType/YachtDriveType.cs" Condition="Exists('$(PkgPath)/Yacht/Schemas/YachtDriveType/YachtDriveType.cs')" />
		<Compile Include="$(PkgPath)/Yacht/Schemas/YachtStatus/YachtStatus.cs" Condition="Exists('$(PkgPath)/Yacht/Schemas/YachtStatus/YachtStatus.cs')" />
	</ItemGroup>
</Project>